-- SparseTree PostgreSQL derived query-store baseline
-- JSON files in data/person remain the Layer 1 source of truth.

-- ============================================================================
-- CORE IDENTITY
-- ============================================================================

CREATE TABLE IF NOT EXISTS person (
    person_id TEXT PRIMARY KEY,
    display_name TEXT NOT NULL,
    birth_name TEXT,
    gender TEXT CHECK (gender IN ('male', 'female', 'unknown')),
    living BOOLEAN NOT NULL DEFAULT FALSE,
    bio TEXT,
    is_unusual_death BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_person_display_name ON person(display_name);
CREATE INDEX IF NOT EXISTS idx_person_gender ON person(gender);
CREATE INDEX IF NOT EXISTS idx_person_unusual_death ON person(is_unusual_death) WHERE is_unusual_death;

CREATE TABLE IF NOT EXISTS external_identity (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_id TEXT NOT NULL REFERENCES person(person_id) ON DELETE CASCADE,
    source TEXT NOT NULL,
    external_id TEXT NOT NULL,
    url TEXT,
    confidence DOUBLE PRECISION DEFAULT 1.0,
    last_seen_at TIMESTAMPTZ,
    UNIQUE (source, external_id)
);

CREATE INDEX IF NOT EXISTS idx_external_identity_person ON external_identity(person_id);
CREATE INDEX IF NOT EXISTS idx_external_identity_source ON external_identity(source);
CREATE INDEX IF NOT EXISTS idx_external_identity_lookup ON external_identity(source, external_id);
CREATE INDEX IF NOT EXISTS idx_external_identity_person_source ON external_identity(person_id, source);

-- ============================================================================
-- RELATIONSHIPS
-- ============================================================================

CREATE TABLE IF NOT EXISTS parent_edge (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    child_id TEXT NOT NULL REFERENCES person(person_id) ON DELETE CASCADE,
    parent_id TEXT NOT NULL REFERENCES person(person_id) ON DELETE CASCADE,
    parent_role TEXT CHECK (parent_role IN ('father', 'mother', 'parent')),
    confidence DOUBLE PRECISION DEFAULT 1.0,
    source TEXT,
    UNIQUE (child_id, parent_id)
);

CREATE INDEX IF NOT EXISTS idx_parent_edge_child ON parent_edge(child_id);
CREATE INDEX IF NOT EXISTS idx_parent_edge_parent ON parent_edge(parent_id);

CREATE TABLE IF NOT EXISTS spouse_edge (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person1_id TEXT NOT NULL REFERENCES person(person_id) ON DELETE CASCADE,
    person2_id TEXT NOT NULL REFERENCES person(person_id) ON DELETE CASCADE,
    marriage_date TEXT,
    marriage_place TEXT,
    divorce_date TEXT,
    confidence DOUBLE PRECISION DEFAULT 1.0,
    source TEXT,
    UNIQUE (person1_id, person2_id)
);

CREATE INDEX IF NOT EXISTS idx_spouse_edge_person1 ON spouse_edge(person1_id);
CREATE INDEX IF NOT EXISTS idx_spouse_edge_person2 ON spouse_edge(person2_id);

-- ============================================================================
-- EVENTS, CLAIMS, AND PROVENANCE
-- ============================================================================

CREATE TABLE IF NOT EXISTS vital_event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_id TEXT NOT NULL REFERENCES person(person_id) ON DELETE CASCADE,
    event_type TEXT NOT NULL CHECK (event_type IN ('birth', 'death', 'burial', 'christening', 'marriage', 'divorce')),
    date_original TEXT,
    date_formal TEXT,
    date_year INTEGER,
    place TEXT,
    place_id TEXT,
    source TEXT,
    confidence DOUBLE PRECISION DEFAULT 1.0,
    UNIQUE (person_id, event_type, source)
);

CREATE INDEX IF NOT EXISTS idx_vital_event_person ON vital_event(person_id);
CREATE INDEX IF NOT EXISTS idx_vital_event_type ON vital_event(event_type);
CREATE INDEX IF NOT EXISTS idx_vital_event_person_type ON vital_event(person_id, event_type);
CREATE INDEX IF NOT EXISTS idx_vital_event_year ON vital_event(date_year);
CREATE INDEX IF NOT EXISTS idx_vital_event_place ON vital_event(place);

CREATE TABLE IF NOT EXISTS claim (
    claim_id TEXT PRIMARY KEY,
    person_id TEXT NOT NULL REFERENCES person(person_id) ON DELETE CASCADE,
    predicate TEXT NOT NULL,
    value_text TEXT,
    value_date TEXT,
    source TEXT,
    confidence DOUBLE PRECISION DEFAULT 1.0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_claim_person ON claim(person_id);
CREATE INDEX IF NOT EXISTS idx_claim_predicate ON claim(predicate);
CREATE INDEX IF NOT EXISTS idx_claim_person_predicate ON claim(person_id, predicate);

CREATE TABLE IF NOT EXISTS life_event (
    event_id TEXT PRIMARY KEY,
    person_id TEXT NOT NULL REFERENCES person(person_id) ON DELETE CASCADE,
    event_type TEXT NOT NULL,
    event_role TEXT NOT NULL DEFAULT 'principal',
    date_original TEXT,
    date_formal TEXT,
    date_year INTEGER,
    date_month INTEGER,
    date_day INTEGER,
    date_end_year INTEGER,
    place_original TEXT,
    place_normalized TEXT,
    place_id TEXT,
    value TEXT,
    description TEXT,
    cause TEXT,
    source TEXT NOT NULL,
    source_id TEXT,
    confidence DOUBLE PRECISION DEFAULT 1.0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_life_event_person ON life_event(person_id);
CREATE INDEX IF NOT EXISTS idx_life_event_type ON life_event(event_type);
CREATE INDEX IF NOT EXISTS idx_life_event_year ON life_event(date_year);
CREATE INDEX IF NOT EXISTS idx_life_event_place ON life_event(place_normalized);
CREATE INDEX IF NOT EXISTS idx_life_event_source ON life_event(source);
CREATE INDEX IF NOT EXISTS idx_life_event_source_id ON life_event(source, source_id);

CREATE TABLE IF NOT EXISTS note (
    note_id TEXT PRIMARY KEY,
    person_id TEXT NOT NULL REFERENCES person(person_id) ON DELETE CASCADE,
    note_type TEXT NOT NULL,
    title TEXT,
    content TEXT NOT NULL,
    content_type TEXT NOT NULL DEFAULT 'text',
    language TEXT NOT NULL DEFAULT 'en',
    source TEXT NOT NULL,
    source_id TEXT,
    author TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_note_person ON note(person_id);
CREATE INDEX IF NOT EXISTS idx_note_type ON note(note_type);
CREATE INDEX IF NOT EXISTS idx_note_source ON note(source);

CREATE TABLE IF NOT EXISTS source_citation (
    citation_id TEXT PRIMARY KEY,
    entity_type TEXT NOT NULL,
    entity_id TEXT NOT NULL,
    source_type TEXT,
    title TEXT,
    author TEXT,
    publisher TEXT,
    publication_date TEXT,
    url TEXT,
    repository TEXT,
    call_number TEXT,
    page TEXT,
    provider TEXT,
    provider_source_id TEXT,
    notes TEXT,
    confidence DOUBLE PRECISION NOT NULL DEFAULT 1.0 CHECK (confidence BETWEEN 0.0 AND 1.0),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_source_citation_entity ON source_citation(entity_type, entity_id);
CREATE INDEX IF NOT EXISTS idx_source_citation_provider ON source_citation(provider, provider_source_id);

CREATE TABLE IF NOT EXISTS local_override (
    override_id TEXT PRIMARY KEY,
    entity_type TEXT NOT NULL,
    entity_id TEXT NOT NULL,
    field_name TEXT NOT NULL,
    original_value TEXT,
    override_value TEXT,
    reason TEXT,
    source TEXT NOT NULL DEFAULT 'local',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (entity_type, entity_id, field_name)
);

CREATE INDEX IF NOT EXISTS idx_local_override_entity ON local_override(entity_type, entity_id);

CREATE TABLE IF NOT EXISTS sync_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_type TEXT NOT NULL,
    entity_id TEXT NOT NULL,
    provider TEXT NOT NULL,
    sync_type TEXT NOT NULL,
    status TEXT NOT NULL,
    records_added INTEGER NOT NULL DEFAULT 0,
    records_updated INTEGER NOT NULL DEFAULT 0,
    records_unchanged INTEGER NOT NULL DEFAULT 0,
    error_message TEXT,
    started_at TIMESTAMPTZ,
    completed_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_sync_log_entity ON sync_log(entity_type, entity_id);
CREATE INDEX IF NOT EXISTS idx_sync_log_provider ON sync_log(provider);

-- ============================================================================
-- DATABASE MEMBERSHIP AND USER STATE
-- ============================================================================

CREATE TABLE IF NOT EXISTS database_info (
    db_id TEXT PRIMARY KEY,
    root_id TEXT REFERENCES person(person_id),
    root_name TEXT,
    source_provider TEXT,
    max_generations INTEGER,
    person_count INTEGER NOT NULL DEFAULT 0,
    is_sample BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS database_membership (
    db_id TEXT NOT NULL,
    person_id TEXT NOT NULL REFERENCES person(person_id) ON DELETE CASCADE,
    is_root BOOLEAN NOT NULL DEFAULT FALSE,
    generation INTEGER,
    PRIMARY KEY (db_id, person_id)
);

CREATE INDEX IF NOT EXISTS idx_database_membership_db ON database_membership(db_id);
CREATE INDEX IF NOT EXISTS idx_database_membership_root ON database_membership(db_id, is_root);

CREATE TABLE IF NOT EXISTS favorite (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    db_id TEXT NOT NULL,
    person_id TEXT NOT NULL REFERENCES person(person_id) ON DELETE CASCADE,
    why_interesting TEXT,
    tags JSONB CHECK (tags IS NULL OR jsonb_typeof(tags) = 'array'),
    added_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (db_id, person_id)
);

CREATE INDEX IF NOT EXISTS idx_favorite_db ON favorite(db_id);
CREATE INDEX IF NOT EXISTS idx_favorite_person ON favorite(person_id);
CREATE INDEX IF NOT EXISTS idx_favorite_added_at ON favorite(added_at DESC);

CREATE TABLE IF NOT EXISTS discovery_dismissed (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    db_id TEXT NOT NULL,
    person_id TEXT NOT NULL REFERENCES person(person_id) ON DELETE CASCADE,
    ai_reason TEXT,
    ai_tags JSONB CHECK (ai_tags IS NULL OR jsonb_typeof(ai_tags) = 'array'),
    dismissed_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (db_id, person_id)
);

CREATE INDEX IF NOT EXISTS idx_discovery_dismissed_db ON discovery_dismissed(db_id);
CREATE INDEX IF NOT EXISTS idx_discovery_dismissed_person ON discovery_dismissed(person_id);

-- ============================================================================
-- MEDIA, ENRICHMENT, AND PLACES
-- ============================================================================

CREATE TABLE IF NOT EXISTS blob (
    blob_hash TEXT PRIMARY KEY,
    path TEXT NOT NULL,
    mime_type TEXT,
    size_bytes BIGINT,
    width INTEGER,
    height INTEGER,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS media (
    media_id TEXT PRIMARY KEY,
    person_id TEXT NOT NULL REFERENCES person(person_id) ON DELETE CASCADE,
    blob_hash TEXT REFERENCES blob(blob_hash) ON DELETE SET NULL,
    source TEXT NOT NULL,
    source_url TEXT,
    is_primary BOOLEAN NOT NULL DEFAULT FALSE,
    caption TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_media_person ON media(person_id);
CREATE INDEX IF NOT EXISTS idx_media_primary ON media(person_id, is_primary);

CREATE TABLE IF NOT EXISTS description (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_id TEXT NOT NULL REFERENCES person(person_id) ON DELETE CASCADE,
    text TEXT NOT NULL,
    source TEXT NOT NULL,
    language TEXT NOT NULL DEFAULT 'en',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (person_id, source)
);

CREATE INDEX IF NOT EXISTS idx_description_person ON description(person_id);

CREATE TABLE IF NOT EXISTS provider_mapping (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_id TEXT NOT NULL REFERENCES person(person_id) ON DELETE CASCADE,
    provider TEXT NOT NULL,
    account_id TEXT,
    match_method TEXT,
    match_confidence DOUBLE PRECISION DEFAULT 1.0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (person_id, provider)
);

CREATE INDEX IF NOT EXISTS idx_provider_mapping_person ON provider_mapping(person_id);

CREATE TABLE IF NOT EXISTS place_geocode (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    place_text TEXT NOT NULL UNIQUE,
    lat DOUBLE PRECISION,
    lng DOUBLE PRECISION,
    display_name TEXT,
    geocode_status TEXT NOT NULL DEFAULT 'pending'
        CHECK (geocode_status IN ('pending', 'resolved', 'not_found', 'error')),
    geocoded_at TIMESTAMPTZ,
    source TEXT NOT NULL DEFAULT 'nominatim'
);

CREATE INDEX IF NOT EXISTS idx_place_geocode_text ON place_geocode(place_text);
CREATE INDEX IF NOT EXISTS idx_place_geocode_status ON place_geocode(geocode_status);

-- ============================================================================
-- SEARCH
-- ============================================================================

CREATE TABLE IF NOT EXISTS person_search (
    person_id TEXT PRIMARY KEY REFERENCES person(person_id) ON DELETE CASCADE,
    display_name TEXT NOT NULL,
    birth_name TEXT NOT NULL DEFAULT '',
    aliases TEXT NOT NULL DEFAULT '',
    bio TEXT NOT NULL DEFAULT '',
    occupations TEXT NOT NULL DEFAULT '',
    search_document TSVECTOR GENERATED ALWAYS AS (
        setweight(to_tsvector('simple'::REGCONFIG, COALESCE(display_name, '')), 'A') ||
        setweight(to_tsvector('simple'::REGCONFIG, COALESCE(birth_name, '')), 'A') ||
        setweight(to_tsvector('simple'::REGCONFIG, COALESCE(aliases, '')), 'B') ||
        setweight(to_tsvector('english'::REGCONFIG, COALESCE(bio, '')), 'C') ||
        setweight(to_tsvector('english'::REGCONFIG, COALESCE(occupations, '')), 'B')
    ) STORED
);

CREATE INDEX IF NOT EXISTS idx_person_search_document ON person_search USING GIN(search_document);

-- ============================================================================
-- AUDITOR
-- ============================================================================

CREATE TABLE IF NOT EXISTS audit_run (
    run_id TEXT PRIMARY KEY,
    db_id TEXT NOT NULL,
    root_person_id TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'queued'
        CHECK (status IN ('queued', 'running', 'paused', 'completed', 'cancelled', 'error')),
    config JSONB NOT NULL,
    cursor JSONB,
    started_at TIMESTAMPTZ,
    paused_at TIMESTAMPTZ,
    completed_at TIMESTAMPTZ,
    persons_checked INTEGER NOT NULL DEFAULT 0,
    issues_found INTEGER NOT NULL DEFAULT 0,
    fixes_applied INTEGER NOT NULL DEFAULT 0,
    error_message TEXT
);

CREATE INDEX IF NOT EXISTS idx_audit_run_db ON audit_run(db_id);
CREATE INDEX IF NOT EXISTS idx_audit_run_status ON audit_run(status);

CREATE TABLE IF NOT EXISTS audit_issue (
    issue_id TEXT PRIMARY KEY,
    run_id TEXT NOT NULL REFERENCES audit_run(run_id) ON DELETE CASCADE,
    person_id TEXT NOT NULL,
    issue_type TEXT NOT NULL,
    severity TEXT NOT NULL CHECK (severity IN ('error', 'warning', 'info', 'hint')),
    description TEXT NOT NULL,
    current_value TEXT,
    suggested_value TEXT,
    suggested_source TEXT,
    status TEXT NOT NULL DEFAULT 'open'
        CHECK (status IN ('open', 'accepted', 'rejected', 'auto_applied')),
    resolved_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_audit_issue_run ON audit_issue(run_id);
CREATE INDEX IF NOT EXISTS idx_audit_issue_person ON audit_issue(person_id);
CREATE INDEX IF NOT EXISTS idx_audit_issue_type ON audit_issue(issue_type);
CREATE INDEX IF NOT EXISTS idx_audit_issue_status ON audit_issue(status);
CREATE INDEX IF NOT EXISTS idx_audit_issue_severity ON audit_issue(severity);

CREATE TABLE IF NOT EXISTS audit_change (
    change_id TEXT PRIMARY KEY,
    issue_id TEXT REFERENCES audit_issue(issue_id) ON DELETE SET NULL,
    person_id TEXT NOT NULL,
    table_name TEXT NOT NULL,
    field TEXT NOT NULL,
    old_value TEXT,
    new_value TEXT,
    applied_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_audit_change_issue ON audit_change(issue_id);
CREATE INDEX IF NOT EXISTS idx_audit_change_person ON audit_change(person_id);

-- ============================================================================
-- CAUSE-OF-DEATH CLASSIFICATION AND MIGRATION TRACKING
-- ============================================================================

CREATE TABLE IF NOT EXISTS unusual_death_keyword (
    keyword TEXT PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO unusual_death_keyword (keyword) VALUES
    ('slain'), ('slew'), ('killed in battle'), ('murdered'), ('assassinated'),
    ('beheaded'), ('decapitated'), ('executed'), ('hanged'), ('guillotin'),
    ('crucified'), ('stabbed'), ('shot'), ('gunshot'), ('poisoned'),
    ('strangled'), ('drowned'), ('devoured'), ('eaten by'), ('mauled'),
    ('trampled'), ('crushed'), ('fell from'), ('fell into'), ('thrown from'),
    ('gored'), ('plague'), ('leprosy'), ('consumption'), ('cholera'),
    ('struck by lightning'), ('lightning'), ('froze to death'), ('starved'),
    ('burned to death'), ('burnt to death'), ('consumed by fire'), ('dragon'),
    ('serpent'), ('wolves'), ('bear '), ('shipwreck'), ('duel'),
    ('broken heart'), ('died of grief'), ('mining accident'), ('train accident'),
    ('railway accident'), ('martyrdom'), ('martyred'), ('suicide')
ON CONFLICT (keyword) DO NOTHING;

CREATE TABLE IF NOT EXISTS migration (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    applied_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO migration (name)
VALUES ('postgres_001_baseline')
ON CONFLICT (name) DO NOTHING;

-- ============================================================================
-- VIEWS AND TIMESTAMP TRIGGERS
-- ============================================================================

CREATE OR REPLACE VIEW person_computed AS
SELECT
    person.person_id,
    person.display_name,
    person.gender,
    birth.date_year AS birth_year,
    birth.place_original AS birth_place,
    death.date_year AS death_year,
    death.place_original AS death_place,
    death.cause AS death_cause,
    CASE
        WHEN birth.date_year IS NOT NULL AND death.date_year IS NOT NULL
        THEN death.date_year - birth.date_year
    END AS age_at_death,
    (SELECT COUNT(*) FROM parent_edge WHERE parent_id = person.person_id) AS child_count,
    (SELECT MIN(date_year) FROM life_event
     WHERE person_id = person.person_id AND event_type = 'http://gedcomx.org/Marriage') AS first_marriage_year,
    CASE
        WHEN birth.date_year IS NOT NULL THEN
            (SELECT MIN(date_year) FROM life_event
             WHERE person_id = person.person_id AND event_type = 'http://gedcomx.org/Marriage') - birth.date_year
    END AS age_at_first_marriage,
    (SELECT value FROM life_event
     WHERE person_id = person.person_id AND event_type = 'data:,TitleOfNobility'
     ORDER BY created_at, event_id LIMIT 1) AS title_of_nobility,
    (SELECT value FROM life_event
     WHERE person_id = person.person_id AND event_type = 'http://gedcomx.org/Occupation'
     ORDER BY created_at, event_id LIMIT 1) AS primary_occupation,
    (SELECT value FROM life_event
     WHERE person_id = person.person_id AND event_type = 'http://gedcomx.org/MilitaryService'
     ORDER BY created_at, event_id LIMIT 1) AS military_service,
    EXISTS (
        SELECT 1 FROM note
        WHERE person_id = person.person_id AND note_type = 'life_sketch'
    ) AS has_life_sketch
FROM person
LEFT JOIN LATERAL (
    SELECT date_year, place_original
    FROM life_event
    WHERE person_id = person.person_id AND event_type = 'http://gedcomx.org/Birth'
    ORDER BY created_at, event_id
    LIMIT 1
) AS birth ON TRUE
LEFT JOIN LATERAL (
    SELECT date_year, place_original, cause
    FROM life_event
    WHERE person_id = person.person_id AND event_type = 'http://gedcomx.org/Death'
    ORDER BY created_at, event_id
    LIMIT 1
) AS death ON TRUE;

CREATE OR REPLACE FUNCTION sparsetree_set_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$;

DO $trigger$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_trigger
        WHERE tgname = 'trg_person_updated_at'
          AND tgrelid = 'person'::REGCLASS
    ) THEN
        CREATE TRIGGER trg_person_updated_at
        BEFORE UPDATE ON person
        FOR EACH ROW EXECUTE FUNCTION sparsetree_set_updated_at();
    END IF;
END
$trigger$;

DO $trigger$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_trigger
        WHERE tgname = 'trg_life_event_updated_at'
          AND tgrelid = 'life_event'::REGCLASS
    ) THEN
        CREATE TRIGGER trg_life_event_updated_at
        BEFORE UPDATE ON life_event
        FOR EACH ROW EXECUTE FUNCTION sparsetree_set_updated_at();
    END IF;
END
$trigger$;

DO $trigger$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_trigger
        WHERE tgname = 'trg_note_updated_at'
          AND tgrelid = 'note'::REGCLASS
    ) THEN
        CREATE TRIGGER trg_note_updated_at
        BEFORE UPDATE ON note
        FOR EACH ROW EXECUTE FUNCTION sparsetree_set_updated_at();
    END IF;
END
$trigger$;

DO $trigger$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_trigger
        WHERE tgname = 'trg_local_override_updated_at'
          AND tgrelid = 'local_override'::REGCLASS
    ) THEN
        CREATE TRIGGER trg_local_override_updated_at
        BEFORE UPDATE ON local_override
        FOR EACH ROW EXECUTE FUNCTION sparsetree_set_updated_at();
    END IF;
END
$trigger$;

CREATE OR REPLACE FUNCTION sparsetree_touch_database_info()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    UPDATE database_info
    SET updated_at = CURRENT_TIMESTAMP
    WHERE db_id = NEW.db_id;
    RETURN NEW;
END;
$$;

DO $trigger$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_trigger
        WHERE tgname = 'trg_database_membership_insert'
          AND tgrelid = 'database_membership'::REGCLASS
    ) THEN
        CREATE TRIGGER trg_database_membership_insert
        AFTER INSERT ON database_membership
        FOR EACH ROW EXECUTE FUNCTION sparsetree_touch_database_info();
    END IF;
END
$trigger$;
